# Exploration des données de Solagro

In [8]:
import pandas as pd 
import polars as pl
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
# Import des données
ift = pd.read_csv(
    "../data/pack_solagro_adonis/pack_solagro_adonis_2020-2022_csv_utf8/fre-324510908-adonis-ift-2022-v04112024.csv",
    sep=";", low_memory=False, index_col=0
)
ift.shape
ift.head()

,id,nom,nom_m,insee_com,sau,sau_bio,cod_c_maj,cod_c_hbc,cod_c_h,c_maj,...,c_ift_h,ift_t,ift_t_hbc,ift_h,ift_t_hh,ift_hh_hbc,iftbc,p_bio,p_bc,p_sau
0,COMMUNE_0000000009750236,L'Abergement-Clémenciat,L'ABERGEMENT-CLEMENCIAT,01001,945.68,30.16,MIS,BTH,MIS,Maïs,...,Maïs,2.30,2.25,0.99,1.32,1.27,0.05,3.19,2.10,60.54
1,COMMUNE_0000000009750692,L'Abergement-de-Varey,L'ABERGEMENT-DE-VAREY,01002,158.10,23.93,PPH,Vigne,Vigne,Prairie permanente,...,Vigne,0.50,0.39,0.02,0.48,0.37,0.11,15.14,21.43,17.23
2,COMMUNE_0000000009750944,Ambérieu-en-Bugey,AMBERIEU-EN-BUGEY,01004,181.57,81.76,PPH,MIS,MIS,Prairie permanente,...,Maïs,0.58,0.56,0.26,0.33,0.30,0.02,45.03,4.28,7.41
3,COMMUNE_0000000009750958,Ambérieux-en-Dombes,AMBERIEUX-EN-DOMBES,01005,1017.84,NaN,MIS,BTH,MIS,Maïs,...,Maïs,2.30,2.26,1.05,1.23,1.21,0.04,NaN,1.71,63.56
4,COMMUNE_0000000009751732,Ambléon,AMBLEON,01006,125.88,29.54,PPH,BTH,BTH,Prairie permanente,...,Blé tendre,0.22,0.21,0.09,0.13,0.12,0.00,23.47,1.98,20.87

In [10]:
# Type des données
ift.info()

<class 'pandas.DataFrame'>
RangeIndex: 34938 entries, 0 to 34937
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          34938 non-null  str
 1   nom         34938 non-null  str
 2   nom_m       34938 non-null  str
 3   insee_com   34938 non-null  str
 4   sau         34607 non-null  float64
 5   sau_bio     25627 non-null  float64
 6   cod_c_maj   34607 non-null  str
 7   cod_c_hbc   34607 non-null  str
 8   cod_c_h     34938 non-null  str
 9   c_maj       34938 non-null  str
 10  c_ift_hbc   34938 non-null  str
 11  c_ift_h     34938 non-null  str
 12  ift_t       34607 non-null  float64
 13  ift_t_hbc   34607 non-null  float64
 14  ift_h       34607 non-null  float64
 15  ift_t_hh    34607 non-null  float64
 16  ift_hh_hbc  34607 non-null  float64
 17  iftbc       34607 non-null  float64
 18  p_bio       25627 non-null  float64
 19  p_bc        32851 non-null  float64
 20  p_sau       34607 non-null  float64
dtypes: float64(11), str(10)
memory usage: 8.8 MB

In [11]:
# exploration du df
ift.describe()

,sau,sau_bio,ift_t,ift_t_hbc,ift_h,ift_t_hh,ift_hh_hbc,iftbc,p_bio,p_bc,p_sau
count,34607.000000,25627.000000,34607.000000,34607.000000,34607.000000,34607.000000,34607.000000,34607.000000,25627.000000,32851.000000,34607.000000
mean,818.613776,104.754100,2.654185,2.522717,0.793663,1.845991,1.729005,0.131285,13.762815,3.661922,54.259536
std,966.512304,208.481404,2.314613,2.101059,0.617907,1.961665,1.696742,0.413562,16.092134,7.727892,23.044828
min,0.130000,0.000000,0.000000,0.000000,-0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,311.305000,14.545000,0.770000,0.740000,0.220000,0.440000,0.440000,0.000000,2.750000,0.170000,37.825000
50%,562.510000,51.050000,2.190000,2.130000,0.730000,1.310000,1.270000,0.010000,8.220000,0.700000,57.610000
75%,994.530000,128.190000,4.070000,3.920000,1.250000,2.710000,2.630000,0.040000,18.620000,2.360000,72.760000
max,45925.990000,17899.590000,22.400000,20.500000,2.690000,22.000000,20.100000,6.260000,100.630000,77.550000,151.980000

In [12]:
# Types de cultures
ift["c_maj"].unique()

<ArrowStringArray>
[                                                 'Maïs',
                                    'Prairie permanente',
                                             'Tournesol',
                                            'Blé tendre',
            'Autre prairie temporaire de 5 ans ou moins',
                               'Surface pastorale (SPH)',
         'Surface agricole temporairement non exploitée',
                                                 'Vigne',
                                          'Orge d'hiver',
                                                'Aucune',
                                                 'Colza',
                      'Betterave non fourragère / Bette',
                                     'Orge de printemps',
                             'Jachère de 5 ans ou moins',
                        'Pomme de terre de consommation',
                                         'Autre luzerne',
                              'Jachère de 6 ans ou plus',
            'Prairie en rotation longue (6 ans ou plus)',
                                             'Triticale',
                                           'Bois pâturé',
                               'Surface pastorale (SPL)',
                                    'Lavande / Lavandin',
                                               'Blé dur',
                               'Mélange de légumineuses',
                                             'Oliveraie',
                               'Vigne : raisins de cuve',
                          'Autre légume ou fruit annuel',
                                             'Châtaigne',
                                                'Sorgho',
     'Mélange de légumineuses fourragères (entre elles)',
                           'Ray-grass de 5 ans ou moins',
                   'Mélange de légumineuses fourragères',
                                                  'Soja',
                                               'Chênaie',
                                                'Tomate',
                                        'Autre sainfoin',
                                                   'Riz',
                                         'Maïs ensilage',
                                         'Marais salant',
                                              'Sarrasin',
                                                  'Chou',
                                             'Artichaut',
                                                  'Noix',
                                   'Mélange de céréales',
                                                'Avoine',
                                   'Luzerne déshydratée',
                                            'Lin fibres',
                                            'Miscanthus',
                                                'Agrume',
                                         'Châtaigneraie',
                                           'Pois chiche',
                   'Laitue / Batavia / Feuille de chêne',
                                          'Autre trèfle',
                                             'Coriandre',
                                   'Haricot / Flageolet',
                                             'Maïs doux',
                                              'Noisette',
                                             'Pépinière',
                                              'Féverole',
                         'Autre légume ou fruit pérenne',
                                     'Petit fruit rouge',
                                               'Poireau',
                                                 'Radis',
                                                 'Mâche',
                      'Prune d’Ente pour transformation',
                                     'Pois protéagineux',
                                              'Épeautre',
                                        'Seigle d’hiver',
                                           'Petits pois',
                                                'Céleri',
        'Surface boisée sur une ancienne terre agricole',
                  'Cerise bigarreau pour transformation',
                                         'Canne à sucre',
                                                'Banane',
                                          'Café / Cacao',
 'Autre culture non précisée dans la liste (admissible)',
                                     'Vergers tropicaux',
                     'Cultures conduites en interrangs ']
Length: 78, dtype: str

In [13]:
# Types de cultures
ift["cod_c_maj"].unique()

<ArrowStringArray>
[  'MIS',   'PPH',   'TRN',   'BTH',   'PTR',   'SPH',   'SNE', 'Vigne',
   'ORH',     nan,   'CZH',   'BTN',   'ORP',   'J5M', 'PTC_C',   'LUZ',
   'J6S',   'PRL',   'TTH',   'BOP',   'SPL',   'LAV',   'BDH',   'VRG',
   'MLG',   'OLI',   'VRC',   'FLA',   'CTG',   'SOG',   'MLF',   'RGA',
   'MLC',   'SOJ',   'CEE',   'TOT',   'SAI',   'RIZ',   'MIE',   'MRS',
   'SRS',   'CHU',   'ART',   'NOX',   'MCR',   'AVP',   'LUD',   'LIF',
   'BTP',   'MCT',   'AGR',   'CAE',   'PCH',   'LBF',   'TRE',   'CRD',
   'J6P',   'HAR',   'MID',   'NOS',   'PEP',   'FVL',   'FLP',   'PFR',
   'POR',   'RDI',   'MAC',   'PRU',   'PPR',   'EPE',   'SGH',   'PPO',
   'CEL',   'AVH',   'SBO',   'CBT',   'CSR',   'CSA',   'BEP',   'CAC',
   'BEF',   'ACA', 'MNG_D',   'CSF', 'GOY_D',   'CSP',   'CIT', 'LET_D']
Length: 88, dtype: str

In [14]:
# Import du fichier rgp_admin
rpg = pl.read_parquet("../data/fichier_admin_parcelles.parquet")
rpg.shape
rpg.head()

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cleabs    ┆ nom_offic ┆ nom_offic ┆ code_inse ┆ … ┆ nom_offic ┆ nom_offic ┆ code_inse ┆ code_sir │
│ ---       ┆ iel       ┆ iel_en_ma ┆ e         ┆   ┆ iel_reg   ┆ iel_en_ma ┆ e_reg     ┆ en_reg   │
│ str       ┆ ---       ┆ juscules  ┆ ---       ┆   ┆ ---       ┆ juscules_ ┆ ---       ┆ ---      │
│           ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ reg       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ COMMUNE_0 ┆ L'Abergem ┆ L'ABERGEM ┆ 01001     ┆ … ┆ Auvergne- ┆ AUVERGNE- ┆ 84        ┆ 20005376 │
│ 000000000 ┆ ent-Cléme ┆ ENT-CLEME ┆           ┆   ┆ Rhône-Alp ┆ RHONE-ALP ┆           ┆ 7        │
│ 001001    ┆ nciat     ┆ NCIAT     ┆           ┆   ┆ es        ┆ ES        ┆           ┆          │
│ COMMUNE_0 ┆ L'Abergem ┆ L'ABERGEM ┆ 01002     ┆ … ┆ Auvergne- ┆ AUVERGNE- ┆ 84        ┆ 20005376 │
│ 000000000 ┆ ent-de-Va ┆ ENT-DE-VA ┆           ┆   ┆ Rhône-Alp ┆ RHONE-ALP ┆           ┆ 7        │
│ 001002    ┆ rey       ┆ REY       ┆           ┆   ┆ es        ┆ ES        ┆           ┆          │
│ COMMUNE_0 ┆ Ambérieu- ┆ AMBERIEU- ┆ 01004     ┆ … ┆ Auvergne- ┆ AUVERGNE- ┆ 84        ┆ 20005376 │
│ 000000000 ┆ en-Bugey  ┆ EN-BUGEY  ┆           ┆   ┆ Rhône-Alp ┆ RHONE-ALP ┆           ┆ 7        │
│ 001004    ┆           ┆           ┆           ┆   ┆ es        ┆ ES        ┆           ┆          │
│ COMMUNE_0 ┆ Ambérieux ┆ AMBERIEUX ┆ 01005     ┆ … ┆ Auvergne- ┆ AUVERGNE- ┆ 84        ┆ 20005376 │
│ 000000000 ┆ -en-Dombe ┆ -EN-DOMBE ┆           ┆   ┆ Rhône-Alp ┆ RHONE-ALP ┆           ┆ 7        │
│ 001005    ┆ s         ┆ S         ┆           ┆   ┆ es        ┆ ES        ┆           ┆          │
│ COMMUNE_0 ┆ Ambléon   ┆ AMBLEON   ┆ 01006     ┆ … ┆ Auvergne- ┆ AUVERGNE- ┆ 84        ┆ 20005376 │
│ 000000000 ┆           ┆           ┆           ┆   ┆ Rhône-Alp ┆ RHONE-ALP ┆           ┆ 7        │
│ 001006    ┆           ┆           ┆           ┆   ┆ es        ┆ ES        ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘