In [2]:
import polars as pl

In [20]:
meteo = pl.read_parquet("../../data/meteo/historique/2026/meteo_Pays_de_la_Loire.parquet")
print(meteo.shape)

(112976, 6)

In [22]:
meteo.tail(10)

shape: (10, 6)
┌────────────┬────────────┬──────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ code_insee ┆ time       ┆ temperature_2m_m ┆ temperature_2m_ ┆ precipitation_s ┆ wind_speed_10m_ │
│ ---        ┆ ---        ┆ ax               ┆ min             ┆ um              ┆ max             │
│ str        ┆ str        ┆ ---              ┆ ---             ┆ ---             ┆ ---             │
│            ┆            ┆ f64              ┆ f64             ┆ f64             ┆ f64             │
╞════════════╪════════════╪══════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ 85306      ┆ 2026-03-24 ┆ 17.6             ┆ 2.0             ┆ 0.0             ┆ 28.8            │
│ 85306      ┆ 2026-03-25 ┆ 12.4             ┆ 5.8             ┆ 0.1             ┆ 56.2            │
│ 85306      ┆ 2026-03-26 ┆ 11.8             ┆ 2.0             ┆ 0.4             ┆ 40.3            │
│ 85306      ┆ 2026-03-27 ┆ 12.9             ┆ 0.5             ┆ 0.0             ┆ 20.9            │
│ 85306      ┆ 2026-03-28 ┆ null             ┆ null            ┆ null            ┆ null            │
│ 85306      ┆ 2026-03-29 ┆ null             ┆ null            ┆ null            ┆ null            │
│ 85306      ┆ 2026-03-30 ┆ null             ┆ null            ┆ null            ┆ null            │
│ 85306      ┆ 2026-03-31 ┆ null             ┆ null            ┆ null            ┆ null            │
│ 85306      ┆ 2026-04-01 ┆ null             ┆ null            ┆ null            ┆ null            │
│ 85306      ┆ 2026-04-02 ┆ null             ┆ null            ┆ null            ┆ null            │
└────────────┴────────────┴──────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [13]:
meteo.describe()

shape: (9, 7)
┌────────────┬────────────┬────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ statistic  ┆ code_insee ┆ time       ┆ temperature_ ┆ temperature_ ┆ precipitatio ┆ wind_speed_1 │
│ ---        ┆ ---        ┆ ---        ┆ 2m_max       ┆ 2m_min       ┆ n_sum        ┆ 0m_max       │
│ str        ┆ str        ┆ str        ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│            ┆            ┆            ┆ f64          ┆ f64          ┆ f64          ┆ f64          │
╞════════════╪════════════╪════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ count      ┆ 448220     ┆ 448220     ┆ 448220.0     ┆ 448220.0     ┆ 448220.0     ┆ 448220.0     │
│ null_count ┆ 0          ┆ 0          ┆ 0.0          ┆ 0.0          ┆ 0.0          ┆ 0.0          │
│ mean       ┆ null       ┆ null       ┆ 17.365734    ┆ 9.580979     ┆ 2.293034     ┆ 39.28818     │
│ std        ┆ null       ┆ null       ┆ 7.04972      ┆ 5.49424      ┆ 4.133236     ┆ 15.35108     │
│ min        ┆ 44001      ┆ 2023-01-01 ┆ 0.9          ┆ -6.4         ┆ 0.0          ┆ 10.8         │
│ 25%        ┆ null       ┆ null       ┆ 12.2         ┆ 5.8          ┆ 0.0          ┆ 28.1         │
│ 50%        ┆ null       ┆ null       ┆ 16.2         ┆ 9.9          ┆ 0.2          ┆ 37.1         │
│ 75%        ┆ null       ┆ null       ┆ 23.0         ┆ 13.7         ┆ 2.8          ┆ 47.2         │
│ max        ┆ 85306      ┆ 2023-12-31 ┆ 36.9         ┆ 24.1         ┆ 53.4         ┆ 125.6        │
└────────────┴────────────┴────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [14]:
# Indicateurs
indicateurs = pl.read_parquet("../../data/parquet/indicateurs_meteo_journaliers_2023_Auvergne-Rhône-Alpes.parquet")
print(indicateurs.shape)

(3650, 6)

In [15]:
indicateurs.head(10)

shape: (10, 6)
┌────────────┬────────────┬──────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ code_insee ┆ time       ┆ indicateur_meteo ┆ interdiction_pu ┆ pluie_limitant_ ┆ risque_dispersi │
│ ---        ┆ ---        ┆ ---              ┆ lv              ┆ dispersion      ┆ on              │
│ str        ┆ str        ┆ i32              ┆ ---             ┆ ---             ┆ ---             │
│            ┆            ┆                  ┆ bool            ┆ bool            ┆ bool            │
╞════════════╪════════════╪══════════════════╪═════════════════╪═════════════════╪═════════════════╡
│ 01001      ┆ 2023-01-01 ┆ 0                ┆ true            ┆ false           ┆ true            │
│ 01001      ┆ 2023-01-02 ┆ 0                ┆ true            ┆ true            ┆ true            │
│ 01001      ┆ 2023-01-03 ┆ 0                ┆ false           ┆ true            ┆ true            │
│ 01001      ┆ 2023-01-04 ┆ 0                ┆ true            ┆ false           ┆ true            │
│ 01001      ┆ 2023-01-05 ┆ 0                ┆ false           ┆ true            ┆ true            │
│ 01001      ┆ 2023-01-06 ┆ 0                ┆ false           ┆ true            ┆ true            │
│ 01001      ┆ 2023-01-07 ┆ 0                ┆ true            ┆ false           ┆ true            │
│ 01001      ┆ 2023-01-08 ┆ 0                ┆ true            ┆ true            ┆ true            │
│ 01001      ┆ 2023-01-09 ┆ 0                ┆ true            ┆ true            ┆ true            │
│ 01001      ┆ 2023-01-10 ┆ 0                ┆ true            ┆ true            ┆ true            │
└────────────┴────────────┴──────────────────┴─────────────────┴─────────────────┴─────────────────┘

In [16]:
# Indicateurs agrégés
indicateurs_agreges = pl.read_parquet("../../data/parquet/indicateurs_meteo_agreges_2023_Auvergne-Rhône-Alpes.parquet")
print(indicateurs_agreges.shape)

(10, 4)

In [17]:
indicateurs_agreges

shape: (10, 4)
┌────────────┬───────────────────────┬──────────────────────────┬─────────────────────┐
│ code_insee ┆ nb_jours_interdiction ┆ nb_jours_pluie_limitante ┆ nb_jours_dispersion │
│ ---        ┆ ---                   ┆ ---                      ┆ ---                 │
│ str        ┆ u32                   ┆ u32                      ┆ u32                 │
╞════════════╪═══════════════════════╪══════════════════════════╪═════════════════════╡
│ 01001      ┆ 326                   ┆ 206                      ┆ 365                 │
│ 01002      ┆ 332                   ┆ 219                      ┆ 365                 │
│ 01004      ┆ 331                   ┆ 198                      ┆ 365                 │
│ 01005      ┆ 323                   ┆ 204                      ┆ 365                 │
│ 01006      ┆ 317                   ┆ 211                      ┆ 365                 │
│ 01007      ┆ 331                   ┆ 198                      ┆ 365                 │
│ 01008      ┆ 331                   ┆ 198                      ┆ 365                 │
│ 01009      ┆ 318                   ┆ 213                      ┆ 365                 │
│ 01010      ┆ 335                   ┆ 221                      ┆ 365                 │
│ 01031      ┆ 327                   ┆ 229                      ┆ 365                 │
└────────────┴───────────────────────┴──────────────────────────┴─────────────────────┘